---
- name: Install Apache HTTPD
  yum:
        name: httpd
        state: present

- name: Deploy Apache web content from template
  template:
        src: index.html.j2
        dest: /var/www/html/index.html
    notify: Restart Apache

- name: Ensure Apache service is running
  systemd:
        name: httpd
        state: started
        enabled: yes