name: tithi job

#trigger Point
# when there is a push happen in master branch pipeline gonna trigger
on: 
  push:
    branches: [ "main" ]  
    paths-ignore:
      - "README.md"

#Creating Jobs

jobs:
# stage 1 with terraform details 
  infra-provission-job:
    runs-on: ubuntu-latest 
    steps: # what exactly you want to run in ubuntu machine 
    #taking my code
    - name: take my code
      uses: actions/checkout@v5
      with:
        ref: main
    #installing terraform
    - name: installing terraform
      uses: hashicorp/setup-terraform@v3
    #github actions
    - name: my first step to test github action
      run: |
        echo "Hello world"
        git version 
        whoami
        ls -a 
        terraform version
#configure aws secret keys

    - name: connecting with aws
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_SECRET_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "ap-southeast-2"
      
    - name: verify aws connection 
      run: |
        echo "checking with command"
        aws s3 ls
    
    - name: deploy terraform resources
      run: |
        echo "implementing terraform deals"
        terraform init 
        terraform plan
        sleep 2
        terraform apply --auto-approve
        ls modules/ec2
    #Creating artifact and upload the inventory file
    - name: uploading ansible inventory to github artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tithi-artifact
        path: |
          modules/ec2/ansible-inventory.txt
          modules/ec2/tithi-private-key.pem


#ansible part    
  infra-configure-job:
    needs: infra-provission-job
    runs-on: ubuntu-latest 
    steps:
    - name: take my code
      uses: actions/checkout@v5
      with:
        ref: main
        sparse-checkout: |
          my-ansible
    - name: verify checkout
      run: |
        ls -R
    - name: connecting with aws
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_SECRET_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "ap-southeast-2"
    #downloading artifact
    - name: downloading single artifact
      uses: actions/download-artifact@v5
      with:
        name: tithi-artifact
    #listing artifact
    - name: display the structure of downloaded file 
      run: ls -R
    #installing ansible
    - name: installing ansible
      run: |
        echo "setup ansible in ubuntu machine"
        sudo apt update
        sudo apt install ansible -y
        ansible --version
    - name: running ansible playbook in dynamic inventory
      run: |
        echo "running ansible playbook"
        chmod 400 tithi-private-key.pem
        cd my-ansible
        ansible-playbook -i ../ansible-inventory.txt --private-key ../tithi-private-key.pem playbook1.yaml




    # #destroying
    # - name: destroy terraform
    #   run: |
    #     echo "destroying aws job"
    #     terraform init 
    #     terraform state list
    #     terraform destroy --auto-approve


    





