name: tithi job

#trigger Point
# when there is a push happen in master branch pipeline gonna trigger
on: 
  push:
    branches: [ "dryrun_aws" ]  
    paths-ignore:
      - "README.md"

#Creating Jobs

jobs:
# stage 1 with terraform details 
  infra-build:
    runs-on: ubuntu-latest 
    steps: # what exactly you want to run in ubuntu machine 
    - name: my first step to test gothub action
      run: |
        echo "Hello world"
        git version 
        whoami
        ls -a 
        terraform version
        docker version
