name: tithi job

#trigger Point
# when there is a push happen in master branch pipeline gonna trigger
on: 
  push:
    branches: [ "main1" ]  
    paths-ignore:
      - "README.md"

#Creating Jobs

jobs:
# stage 1 with terraform details 
  infra-provission-job:
    runs-on: ubuntu-latest 
    steps: # what exactly you want to run in ubuntu machine 
    #taking my code
    - name: take my code
      uses: actions/checkout@v5
      with:
        ref: main
    #installing terraform
    - name: installing terraform
      uses: hashicorp/setup-terraform@v3
    #github actions
    - name: my first step to test github action
      run: |
        echo "Hello world"
        git version 
        whoami
        ls -a 
        terraform version
#configure aws secret keys

    - name: connecting with aws
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_SECRET_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "ap-southeast-2"
      
    - name: verify aws connection 
      run: |
        echo "checking with command"
        aws s3 ls
    
    - name: deploy terraform resources
      run: |
        echo "implementing terraform deals"
        terraform init 
        terraform plan
        sleep 2
        terraform apply --auto-approve
    
  infra-destroy-job:
    needs: infra-provission-job
    runs-on: ubuntu-latest 
    steps:
    - name: take my code
      uses: actions/checkout@v5
      with:
        ref: main
    - name: connecting with aws
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_SECRET_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "ap-southeast-2"
    #installing terraform
    - name: installing terraform
      uses: hashicorp/setup-terraform@v3
    #destroying
    - name: destroy terraform
      run: |
        echo "destroying aws job"
        terraform init 
        terraform state list
        terraform destroy --auto-approve


    





